// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function BuildQTPrompt(arg1:service.LLMPrepareRequest):Promise<string>;

export function GeneratePNG(arg1:number):Promise<service.PNGGenerateResult>;

export function GetVideoMeta(arg1:string):Promise<service.VideoMeta>;

export function LoadQTStep2Data():Promise<service.QTStep2Data>;

export function LoadTextFile(arg1:string):Promise<string>;

export function OpenOutputFile(arg1:string):Promise<void>;

export function OpenTempHTMLPreview():Promise<void>;

export function PreviewQTStep2HTML(arg1:service.QTStep2Data):Promise<service.QTStep2PreviewResult>;

export function RunLLMPrepare(arg1:service.LLMPrepareRequest):Promise<service.LLMPrepareResult>;

export function RunQTStep3(arg1:service.QTStep3Request):Promise<service.QTStep3Result>;

export function RunSourcePrepare(arg1:service.SourcePrepareRequest):Promise<service.SourcePrepareResult>;

export function SaveManualLLMResult(arg1:string):Promise<void>;

export function SaveQTOutputAs(arg1:service.SaveOutputAsRequest):Promise<service.SaveOutputAsResult>;

export function SaveQTStep2Data(arg1:service.QTStep2Data):Promise<void>;

export function SelectAudioFile():Promise<string>;

export function SelectTextFile():Promise<string>;
