// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildQTPrompt(arg1) {
  return window['go']['main']['App']['BuildQTPrompt'](arg1);
}

export function GeneratePNG(arg1) {
  return window['go']['main']['App']['GeneratePNG'](arg1);
}

export function GetVideoMeta(arg1) {
  return window['go']['main']['App']['GetVideoMeta'](arg1);
}

export function LoadQTStep2Data() {
  return window['go']['main']['App']['LoadQTStep2Data']();
}

export function LoadTextFile(arg1) {
  return window['go']['main']['App']['LoadTextFile'](arg1);
}

export function OpenOutputFile(arg1) {
  return window['go']['main']['App']['OpenOutputFile'](arg1);
}

export function OpenTempHTMLPreview() {
  return window['go']['main']['App']['OpenTempHTMLPreview']();
}

export function PreviewQTStep2HTML(arg1) {
  return window['go']['main']['App']['PreviewQTStep2HTML'](arg1);
}

export function RunLLMPrepare(arg1) {
  return window['go']['main']['App']['RunLLMPrepare'](arg1);
}

export function RunQTStep3(arg1) {
  return window['go']['main']['App']['RunQTStep3'](arg1);
}

export function RunSourcePrepare(arg1) {
  return window['go']['main']['App']['RunSourcePrepare'](arg1);
}

export function SaveManualLLMResult(arg1) {
  return window['go']['main']['App']['SaveManualLLMResult'](arg1);
}

export function SaveQTOutputAs(arg1) {
  return window['go']['main']['App']['SaveQTOutputAs'](arg1);
}

export function SaveQTStep2Data(arg1) {
  return window['go']['main']['App']['SaveQTStep2Data'](arg1);
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function SelectTextFile() {
  return window['go']['main']['App']['SelectTextFile']();
}
